name: Update history

on:
  pull_request:
    branches:
      - main

jobs:
  update_history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Write to history
        run: |
          echo "${{ github.actor }},user1@gmail.com,${{ github.event.pull_request.created_at }}" >> history.csv
        
        
      - name: switching from HTTPS to SSH
        run: |
          git remote set-url origin git@github.com:letu0712/TestWorkflow_WriteFile.git
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating history.csv"
      - name: fetch from feature
        run: git fetch origin feature
      - name: push code to feature
        run: git push origin HEAD:feature